export const TYPES= {
    READ_STATE: "READ_STATE",
    ADD_TO_CART: "ADD_TO_CART", //AGREGAR UN PRODUCTO AL CARRITO
    REMOVE_ITEM: "REMOVE_ITEM",//BORRAR UN PRODUCTO DEL CARRITO
    REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",// BORRAR TODA LA CANTIDAD DE UN PRODUCTO
    CLEAR_CART: "CLEAR_CART"// VUELVE A ESTAR EN CERO

};